# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

Existem diversos tipos básicos numéricos em Python, com o numpy é possível ter uma variedade de tipos muito maior. 
Como existem vários tipos de dados é pssível também fazer a conversão de um tipo para outro, para isso são usadas alguns comandos como o astype(), que recebe como parametro o novo tipo de dado que deseja que seja aplicado ao seu dado anterior. Para saber o tipo de um dado basta usar o comando dtype.

In [ ]:
import numpy as np

In [ ]:
x = np.float32(1.0)
x

1.0

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [ ]:
z.astype(float)

array([0., 1., 2.])

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')