# 8 - Leitura e salvamento de conjuntos de dados

## Lendo arquivos de texto puro

Carregando o arquivo de texto e colocando os dados dentro da varivel text

In [1]:
filename = 'huck_finn.txt'

file = open(filename, mode='r')
text = file.read()

file.close()

Printando o que estava escrito dentro da varivel

In [2]:
print(text)

YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt Polly, she is--and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before.


## Criando um contexto para leitura de arquivos

In [3]:
with open('huck_finn.txt', 'r') as file:
    print(file.read())

YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt Polly, she is--and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before.


## Importando dados com o Numpy

In [5]:
import numpy as np

filename = 'MNIST.txt'

data = np.loadtxt(filename, delimiter=',')
data

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [6]:
data = np.loadtxt(filename, delimiter=',', skiprows=1)

In [7]:
print(data)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 ...
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]]


In [8]:
data = np.loadtxt(filename, delimiter=',', skiprows=1, usecols=[0,2])
data

array([[0., 0.],
       [1., 0.],
       [4., 0.],
       [0., 0.],
       [0., 0.],
       [7., 0.],
       [3., 0.],
       [5., 0.],
       [3., 0.],
       [8., 0.],
       [9., 0.],
       [1., 0.],
       [3., 0.],
       [3., 0.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [7., 0.],
       [5., 0.],
       [8., 0.],
       [6., 0.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [3., 0.],
       [6., 0.],
       [9., 0.],
       [9., 0.],
       [7., 0.],
       [8., 0.],
       [9., 0.],
       [4., 0.],
       [9., 0.],
       [2., 0.],
       [1., 0.],
       [3., 0.],
       [1., 0.],
       [1., 0.],
       [4., 0.],
       [9., 0.],
       [1., 0.],
       [4., 0.],
       [4., 0.],
       [2., 0.],
       [6., 0.],
       [3., 0.],
       [7., 0.],
       [7., 0.],
       [4., 0.],
       [7., 0.],
       [5., 0.],
       [1., 0.],
       [9., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [3., 0.],
       [9., 0.],
       [1., 0.

In [9]:
data = np.loadtxt(filename, delimiter=',', dtype=str)
print(data)

[['1.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
 ['0.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
 ['1.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
 ...
 ['2.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
 ['0.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
 ['5.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']]


## Importando arquivos utilizando o Pandas

Em geral, um cientista de dados precisa lidar com
- Estruturas de dados bidimensionais, rotuladas,
- Colunas com tipos potencialmente diferentes,
- Manipulação, fatiamento, reformar, agrupar, juntar,
- Realizar estatísticas,
- Trabalhar com dados de séries temporais,
- ...

Carregando os dados do arquivo .csv

In [12]:
import pandas as pd

filename = 'winequality-red.csv'

data = pd.read_csv(filename)

data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [13]:
data_array = data.values
data_array

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])